version: "3"

services:
  api:
    container_name: gpt_othello
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: uvicorn gpt_othello.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      TZ: "Asia/Tokyo"
      STAGE: ${STAGE:-dev}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - ${API_PORT}:8000
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
